@startuml
left to right direction
actor "User" as usr
package Reservation {
usecase "Search" as uc1
usecase "Scan To Reserve" as uc2
usecase "Pickup" as uc3
usecase "Return Vehicle" as uc4
usecase "Remote Reserve" as uc5
usecase "Cancel" as uc6
usecase "Fetch Hired Vehicles" as uc7
}
usr --> uc1
usr --> uc2
usr --> uc3
usr --> uc4
usr --> uc5
usr --> uc6
usr ->> uc7


left to right direction
actor "System" as sys
package Notification {
usecase "Compute Invoice" as suc1
usecase "Send invoice" as suc2
usecase "Send Booking Reminder" as suc3
usecase "Update Inventory" as suc4
}
sys --> suc1
sys --> suc2
sys --> suc3
sys --> suc4

@enduml